name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - xgboost
    - matplotlib
    - seaborn
    - scipy
    - streamlit>=1.40.0
    - altair<5
    - plotly
    - groq
    - python-dotenv
